### ISSUE TITLE
Createkit command not working on Spigot 1.8

### ISSUE THREAD

**Issue by schneidermr** [EssentialsX/Essentials#848]
I tried to use createkit command on a Spigot 1.8 server, but got an error below that can't detect GSON class.
If I try to add manually kits to the config file, kit and showkit commands working properly.

> [19:22:25] [Server thread/ERROR]: Command createkit failed:
> java.lang.NoClassDefFoundError: com/google/gson/Gson
>   at com.earth2me.essentials.commands.Commandcreatekit.<clinit>(Commandcreatekit.java:42) ~[EssentialsX-2.0.1.jar:?]
>   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_91]
>   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_91]
>   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_91]
>   at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_91]
>   at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_91]
>   at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:434) [EssentialsX-2.0.1.jar:?]
>   at com.earth2me.essentials.Essentials.onCommand(Essentials.java:374) [EssentialsX-2.0.1.jar:?]
>   at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
>   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
>   at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
>   at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
>   at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
>   at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
>   at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
>   at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
>   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
>   at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
>   at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
>   at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
>   at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
>   at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
>   at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
> Caused by: java.lang.ClassNotFoundException: com.google.gson.Gson
>   at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_91]
>   at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
>   at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
>   ... 23 more

**Comment by mdcfe** [comment]
Closing due to inactivity; try updating Spigot, and if this is still a problem then feel free to open a new issue.
